spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
mybatis:
  type-aliases-package: com.app.dto
  mapper-locations: mappers/*.xml